blog/urls.py
from django.urls import path 
from . import views
from django.conf import settings
from django.conf.urls.static import static
from  django.contrib.auth import views as auth_views



app_name = 'blog'

urlpatterns = [

    
    path('',views.blog_list, name='blog_list'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/<int:pk>/', views.profile, name='profile'),
    path('posts_by_tag/<int:tag_id>/', views.posts_by_tag, name='posts_by_tag'),
    path('subcategory/<int:subcategory_id>/', views.posts_for_subcategory, name='subcategory_posts'),
    path('cat&tags/', views.blog_cattags, name='cattags'),
    path('search/', views.search, name='search'),
    path('post/<slug:slug>/like/', views.like_post, name='like_post'),
    path('post/<slug:slug>/favorite/', views.add_to_favorites, name='add_to_favorites'),
    path('create/', views.blog_create, name='blog_create'),
    path('<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('<slug>/update/', views.blog_update, name='blog_update'),
    path('<slug>/delete/', views.blog_delete, name='blog_delete'),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

myBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

class Categories(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Subcategories(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE,null=True, blank=True, related_name='subcategories')

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    content = RichTextField(blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField(Categories)
    subcategory = models.ForeignKey(Subcategories, on_delete=models.CASCADE, null=True, blank=True)
    tags = models.ManyToManyField(Tag)
    image = models.ImageField(upload_to='blog_images/')
    likes = models.ManyToManyField(User, related_name='liked_posts', blank=True)
    favorites = models.ManyToManyField(User, related_name='favorite_posts', blank=True)

    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()

    def total_favorites(self):
        return self.favorites.count()

blog/forms.py
from django import forms
from .models import BlogPost, Categories, Tag, Subcategories

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User 





class BlogPostForm(forms.ModelForm):

 
    class Meta:
        model = BlogPost
        fields = ('title', 'slug', 'content','categories', 'subcategory' ,'tags','image')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'categories': forms.Select(attrs={'class': 'form-control'}),
            'subcategory': forms.Select(attrs={'class': 'form-control'}),
            'tags': forms.Select(attrs={'class': 'form-control'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }








class SignUpForm(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import BlogPost, Categories, Subcategories, Tag
from .forms import BlogPostForm, SignUpForm
from django.db.models import Q
# for user authentication
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User 
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage



#===========================================================================================

# Auth

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:login')
    else:
        form = SignUpForm()
    return render(request, 'blog/signup.html', {'form':form})


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('blog:blog_list')
        else:
            error_message = 'Invalid username or password.'
            return render(request, 'blog/login.html', {'error_message':error_message})
    else:
        return render(request, 'blog/login.html')


@login_required
def logout_view(request):
    logout(request)
    return redirect('blog:blog_list')


@login_required(login_url='blog:login')
def profile(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.user != user:
        return redirect('blog:profile',pk=request.user.pk)
    user_posts = BlogPost.objects.filter(author=user)
    favorites = user.favorite_posts.all()
    context = {
        'user': user,
        'user_posts': user_posts,
        'favorites': favorites,
    }
    return render(request, 'blog/profile.html', context)



#===========================================================================================================

# Posts by tags, and category, Search functionality
def posts_by_tag(request, tag_id):
    tag = get_object_or_404(Tag, pk=tag_id)
    posts = BlogPost.objects.filter(tags=tag)
    categories = Categories.objects.prefetch_related('subcategories')

    for post in posts:
        post.first_three_lines = post.content.split('\n')[3:11]

    # Number of posts to show per page
    posts_per_page = 3  # You can adjust this value

    paginator = Paginator(posts, posts_per_page)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'tag': tag, 'posts': posts, 'categories':categories}
    return render(request, 'blog/posts_by_tag.html', context)



def posts_for_subcategory(request, subcategory_id):
    subcategory = get_object_or_404(Subcategories, pk=subcategory_id)
    posts = BlogPost.objects.filter(subcategory=subcategory)
    categories = Categories.objects.prefetch_related('subcategories')

    for post in posts:
        post.first_three_lines = post.content.split('\n')[3:11]

    # Number of posts to show per page
    posts_per_page = 3  # You can adjust this value

    paginator = Paginator(posts, posts_per_page)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'subcategory':subcategory,
        'posts':posts,
        'categories': categories,

    }

    return render(request, 'blog/post_cat.html', context)


def search(request):
    query = request.GET.get('q', '').strip()  # Get the search query from the request
    categories = Categories.objects.prefetch_related('subcategories')

    if not query:
        results = BlogPost.objects.none()
    else:
        words = query.split()  # Split the query into individual words

        # Create a Q object for each word in the title field
        title_queries = Q()
        for word in words:
            title_queries |= Q(title__icontains=word)

        # Combine the title queries using the OR operator
        results = BlogPost.objects.filter(title_queries)

        for post in results:
            post.first_three_lines = post.content.split('\n')[3:11]

    # Number of results to show per page
    results_per_page = 3  
    paginator = Paginator(results, results_per_page)
    page = request.GET.get('page')

    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        results = paginator.page(1)
    except EmptyPage:
        results = paginator.page(paginator.num_pages)

    context = {
        'query': query,
        'results': results,
        'categories': categories,
    }
    return render(request, 'blog/search_results.html', context)


#==========================================================================================================
# Display blog posts, categories tags, post in detail


def blog_cattags(request):
    categories = Categories.objects.prefetch_related('subcategories')
    tags = Tag.objects.all()
    context = {
        'categories': categories,
        'tags' : tags,

    }
    return render(request, 'blog/cattags.html', context)


def blog_list(request):
    posts = BlogPost.objects.all()
    categories = Categories.objects.prefetch_related('subcategories')

    for post in posts:
        post.first_three_lines = post.content.split('\n')[3:11]

    # Number of posts to show per page
    posts_per_page = 3  # You can adjust this value

    paginator = Paginator(posts, posts_per_page)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/blog_list.html', {'posts': posts, 'categories': categories})


def blog_detail(request, slug):
    print("View is called")
    post = get_object_or_404(BlogPost, slug=slug)
    categories = Categories.objects.prefetch_related('subcategories')
    tl = post.total_likes()
    print(f"Post title: {post.title}") 
    return render(request, 'blog/blog_detail.html', {'post': post, 'tl':tl, 'categories':categories})


#====================================================================================================================

# CRUD, LIKES, FAV

@login_required(login_url='blog:login')
def blog_create(request):

    if request.method == 'POST':
        form = BlogPostForm(request.POST, request.FILES)
        if form.is_valid():
            blog_post = form.save(commit=False)
            blog_post.author = request.user
            blog_post.save()
            form.save_m2m()  # Save the many-to-many relationships (categories and tags)
            return redirect('blog:blog_detail', slug=blog_post.slug)
    else:
        form = BlogPostForm()
    return render(request, 'blog/blog_create.html', {'form': form})


@login_required(login_url='blog:login')
def blog_update(request, slug):
    post = get_object_or_404(BlogPost, slug=slug)
    if request.user != post.author:
        return redirect('blog:blog_detail', slug=slug)
    if request.method == 'POST':
        form = BlogPostForm(request.POST, request.FILES,instance=post)
        if form.is_valid():
            form.save()
            return redirect('blog:blog_detail', slug=post.slug)

    else:
        form = BlogPostForm(instance=post)
    
    return render(request, 'blog/blog_update.html', {'form':form, 'post':post})


@login_required(login_url='blog:login')
def blog_delete(request, slug):
    post = get_object_or_404(BlogPost, slug=slug)
    if request.method == 'POST' and request.user == post.author:
        post.delete()
        return redirect('blog:blog_list')
    return render(request, 'blog/blog_delete.html', {'post': post})

def cattags(request):
    return render(request, 'blog/cat_tag.html')

def contact(request):
    return render(request, "blog/contact.html")


@login_required(login_url='blog:login')
def like_post(request, slug):
    post = get_object_or_404(BlogPost, slug=slug)
    if request.user in post.likes.all():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
        
    return redirect('blog:blog_detail', slug=slug) 

@login_required(login_url='blog:login')
def add_to_favorites(request, slug):
    post = get_object_or_404(BlogPost, slug=slug)
    if request.user in post.favorites.all():
        post.favorites.remove(request.user)
    else:
        post.favorites.add(request.user)
    return redirect('blog:blog_detail', slug=slug)

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <title>{% block title %}{% endblock %}</title>

  <!-- Custom CSS link -->
  
  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300;400;500;600;700;800&display=swap"
    rel="stylesheet">
  <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
  
  <link id="white-theme-stylesheet" rel="stylesheet" href="{% static 'css/blog/style-white.css' %}">
  <link id="black-theme-stylesheet" rel="stylesheet" href="{% static 'css/blog/style-black.css' %}" disabled>

  <!-- Your existing HTML code -->

  <style>
  /* Custom CSS to align the button with other list items */
    .nav-item {
        display: flex;
        align-items: center; /* Vertically align items */
    }
    
    .nav-link {
        line-height: 1.2; /* Adjust line height as needed */
    }

    .theme-switch {
       margin-right: 10px;
       margin-top: 15px; /* Adjust the margin as needed to control the spacing between the switch and other list items */
       margin-bottom: 10px;
      }

  </style>
  
  <style>
    /* CSS to style all anchor tags */
    a {
        text-decoration: none; /* Remove underline */
        color: inherit; /* Inherit text color from parent */
        transition: color 0.2s; /* Add a smooth color transition on hover */
    }
    
    /* CSS to change the text color on hover */
    a:hover {
        color: your-desired-hover-color; /* Change the color on hover */
    }
  </style>
    
    
</head>

<body>

  <nav class="navbar navbar-expand-md border-bottom border-secondary border-opacity-50 fixed-top" style="height: 60px; /* Adjust as needed */">

    <div class="container-fluid">
        


        <a class="navbar-brand d-md-none justify-content-start" href="#"  data-bs-toggle="offcanvas" data-bs-target="#offcanvasLeft" aria-controls="offcanvasLeft">
            <i class="bi bi-three-dots" ></i>
        </a>


        <a class="navbar-brand" href="{% url 'blog:blog_list' %}">

          <img  src="{% static 'images/logo4.svg' %}" alt="Logo" width="30" height="24">
          
        </a>
          

          

      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas"
       data-bs-target="#offcanvasRight" aria-controls="offcanvasRight" 
       aria-expanded="false" aria-label="Toggle Navigation">
       <i class="bi bi-list"></i>
      </button>

      <div class="offcanvas offcanvas-end " tabindex="-1" id="offcanvasRight" data-bs-scroll="true" aria-labelledby="offcanvasRightLabel">

        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasRightLabel">Offcanvas Right</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        
        <div class="offcanvas-body justify-content-evenly  ms-2">

            <ul class="navbar-nav  mb-2 mb-lg-0">



                <li class="nav-item">
                    <a href="{% url 'blog:blog_list' %}" aria-current="page" class="nav-link">Blog</a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'blog:cattags' %}" class="nav-link">Categories</a>
                </li>



                {% if user.is_authenticated %}

                <li class="nav-item">

                <a class="nav-link" href="{% url 'blog:profile' pk=request.user.pk %}">Account</a>

                </li>


                <li class="nav-item">

                  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" style="background: transparent; border: none;" >
                    <i class="bi bi-power text-primary focus-ring "></i>
                  </button>
                  
                 
                  <!-- Modal -->
                  <div class="modal fade modal-black" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h1 class="modal-title fs-5" id="exampleModalLabel">Logout</h1>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>

                        <div class="modal-body">
                          <h5> Are you sure you want to Logout?</h5>
                        </div>

                        <div class="modal-footer">

                          <button type="button" class="btn  btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button"  class="btn btn-danger ">
                              <a  href="{% url 'blog:logout' %}">
                                Logout 
                              </a>
                            </button>

                        </div>
                      </div>
                    </div>
                  </div>
                
                </li>


                
                {% else %}

                <li class="nav-item">

                <a class="nav-link" href="{% url 'blog:login' %}">Sign In</a>

                </li>

                <li class="nav-item">

                  <a class="nav-link" href="{% url 'blog:signup' %}">Sign Up</a>
  
                </li>


                {% endif %}

              <label class="theme-switch ms-2" for="theme-toggle" >
                  <input type="checkbox" id="theme-toggle">
                  <div class="toggle-slider"></div>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-toggle-on" viewBox="0 0 16 16">
                    <path d="M5 3a5 5 0 0 0 0 10h6a5 5 0 0 0 0-10H5zm6 9a4 4 0 1 1 0-8 4 4 0 0 1 0 8z"/>
                  </svg>
              </label>


            </ul>


        </div>

      </div>

    </div>

  </nav>

  <div class="container" style="margin-top: 80px;"> <!-- Add margin-top to create space below the fixed navbar -->
    {% block content %}

    
    {% endblock %}
  </div>


  <!-- Offcanvas (visible on "md" and smaller screens) -->
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasLeft" aria-labelledby="offcanvasLeftLabel">
    


  <div class="offcanvas-header">
    <h5>Sidebar</h5>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  
  <hr>

  <a href="{% url 'blog:blog_list' %}">
      <h6 class="ms-3">
      <i class="bi bi-house"></i> Home
      </h6>
  </a>




  <a href="{% url 'blog:blog_create' %}" class="btn-delete ">
      <h6 style="margin-left: 16px; margin-top: 12px;" >
          <i class="bi bi-plus-circle"></i>  Create
      </h6>
  </a>



  <div style="display: flex;">
      <form class="d-flex search-form" role="search" method="GET" action="{% url 'blog:search' %}">
          <i class="bi bi-search search-color me-1 mt-1 "></i><input class="form-control me-2 search-input" type="search" name="q" placeholder='Search' aria-label="Search">
      </form>      
  </div>

  <hr>

  <h5 class="offcanvas-title" id="offcanvasLeftLabel">Categories</h5>
  <div class="offcanvas-body">
      <div>

          {% for category in categories %}
          <div class="mb-0">
              <button class="btn dropdown-toggle"  data-bs-toggle="collapse" data-bs-target="#categorySection{{ category.id }}">
                  <i class="bi bi-bank2 me-2"></i> {{ category.name }}
              </button>

              <div class="collapse" id="categorySection{{ category.id }}">
                 
                  <ul class="list-unstyled ms-3">

                      {% for subcategory in category.subcategories.all %}
                          <li><a href="#"><span class="subcategory">{{ subcategory.name }}</span></a></li>
                      {% endfor %}

                  </ul>

              </div>
          </div>
          {% endfor %}

      </div>


  </div>

</div>




    
  <script src="{% static 'js/script.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <!-- ionicon link -->
  <script type="module"
    src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule
    src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>


</body>

</html>

blog/templates/blog/blog_create.html
{% extends 'blog/base.html' %}

{% block content %}


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
          
                <h1>Create Blog Post</h1>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Create</button>
                </form>
         
        </div>
    </div>
</div>





{% endblock %}

blog/templates/blog/blog_delete.html
{% extends 'blog/base.html' %}

{% block content %}

  <h1>Delete Blog Post</h1>
  <p>Are you sure you want to delete "{{ post.title }}"?</p>
  <form method="POST">
    {% csrf_token %}
    <button type="submit">Delete</button>
  </form>



{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}

<style>
    .sidebar {
        position: sticky;
        top: 0;
        height: 100vh; /* Adjust this to your preferred height */
        overflow-y: auto;
    }

    .sidebar::-webkit-scrollbar {
        width: 6px; /* Width of the scrollbar */
    }

    .sidebar::-webkit-scrollbar-thumb {
        background-color: #666666; /* Color of the thumb */
        border-radius: 0px; /* Rounded edges for the thumb */
    }

    .sidebar::-webkit-scrollbar-track {
        background-color: #f0f0f0; /* Color of the track */
    }
</style>



<div class="container mt-5">
    <div class="row">
          <!-- Sidebar (visible on larger screens) -->
         
          <nav class="col-md-4 col-lg-3  mt-5  border-secondary border-opacity-10 d-md-block sidebar"  style="height: 100vh; overflow-y: auto;">
            <!-- Sidebar content here (e.g., categories and tags) -->

            <a href="{% url 'blog:blog_list' %}">
              <h6 class="ms-3">
              <i class="bi bi-house"></i> Home
              </h6>
            </a>
          
            
            <!-- <h6 class="ms-3">
                <i class="bi bi-arrow-up-right-circle"></i> Popular
            </h6> -->

            <a href="{% url 'blog:blog_create' %}" class="btn-delete">
                <h6 style="margin-left: 16px;">
                    <i class="bi bi-plus-circle"></i>  Create
                </h6>
            </a>

            <div style="display: flex;">
                <form class="d-flex search-form" role="search" method="GET" action="{% url 'blog:search' %}">
                    <i class="bi bi-search search-color me-1 mt-1 "></i><input class="form-control me-2 search-input" type="search" name="q" placeholder='Search' aria-label="Search">
                </form>      
            </div>



            <hr>

            <h6 class="text-capitalize bg-gradient mb-3">Topics</h6>
            


            <div>

                {% for category in categories|slice:":12" %}
                <div class="mb-0">
                    <button class="btn dropdown-toggle"  data-bs-toggle="collapse" data-bs-target="#categorySection{{ category.id }}">
                        <i class="bi bi-bank2 me-2"></i> {{ category.name }}
                    </button>

                    <div class="collapse" id="categorySection{{ category.id }}">
                       
                        <ul class="list-unstyled ms-3 mt-1">

                            {% for subcategory in category.subcategories.all %}
                                <li><a href="{% url 'blog:subcategory_posts' subcategory.id %}" style="text-decoration: none;"><span class="subcategory">{{ subcategory.name }}</span>  </a></li>
                            {% endfor %}

                        </ul>

                    </div>
                </div>
                {% endfor %}

                {% if categories|length > 12 %}
                <div class="text-center mt-1">
                    <a href="{% url 'blog:cattags' %}" style="text-decoration: none;" class="see-more-link">See More</a>
                </div>
                {% endif %}

            </div>

            <hr>

        </nav>

        <main class="col-md-8 col-lg-8 mt-5 ms-md-5">

                    <h1 class="blog-title">{{ post.title }}</h1>
                    <!-- <img class="blog-image" src="{{ post.image.url }}" alt="{{ post.title }}"> -->
                    <p class="post-meta">Author: {{ post.author }}</p>
                    <p class="post-meta">Categories: {{ post.categories.all|join:', ' }}</p>
                    <p class="post-meta">Subcategory: {{ post.subcategory.name }}</p>
                    <p class="post-meta">Tags: {{ post.tags.all|join:', ' }}</p>
                    <p class="blog-content">{{ post.content|safe }}</p>
                    
                    {% if user.is_authenticated %}
                    {% if user != post.author %}
                    <form method="POST" action="{% url 'blog:like_post' slug=post.slug %}">
                        {% csrf_token %}
                        {% if user in post.likes.all %}
                        <button type="submit" class="btn-unlike">Unlike</button>
                        {% else %}
                        <button type="submit" class="btn-like">Like</button>
                        {% endif %}
                        <p class="total-likes">Total Likes: {{ tl }}</p>
                    </form>
                    <form method="POST" action="{% url 'blog:add_to_favorites' slug=post.slug %}">
                        {% csrf_token %}
                        {% if user in post.favorites.all %}
                        <button type="submit" class="btn-remove-fav">Remove from Favorites</button>
                        {% else %}
                        <button type="submit" class="btn-add-fav">Add to Favorites</button>
                        {% endif %}
                    </form>
                    {% endif %}
                    {% endif %}

                    {% if user.is_authenticated and user == post.author %}
                    <p>
                        <a href="{% url 'blog:blog_update' slug=post.slug %}" class="btn-edit">Edit</a>
                        <a href="{% url 'blog:blog_delete' slug=post.slug %}" class="btn-delete">Delete</a>
                    </p>
                    {% endif %}
         
        
        </main>

    </div>
</div>


  

{% endblock %}

blog/templates/blog/blog_update.html
{% extends 'blog/base.html' %}

{% block content %}




<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-6">
        
        <h1>Edit Blog Post</h1>
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.media }}
          {{ form.as_p }}
          <button type="submit">Update</button>
        </form>
       
      </div>
  </div>
</div>

{% endblock %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}

{% block content %}
          


          

              {% if error_message %}
                <p>{{ error_message }}</p>
              {% endif %}

              <div class="container">
                <div class="row justify-content-center">
                  <div class="col-md-6 col-lg-4 m-lg-5 m-md-5">
                    <div class="card shadow black-card">
                      <div class="card-header">
                        LOGIN
                      </div>
                      <div class="card-body">
                        <form method="post">
                          {% csrf_token %}
                          <div class="mb-3">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" class="form-control" id="username" name="username" placeholder="Enter your username">
                          </div>
                          <div class="mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password" placeholder="Enter your password">
                          </div>

                          <div class="text-center">
                              <button class="btn btn-primary btn-block" type="submit">Login</button>
                          </div>

                          <p class="mt-3 text-center">Don't have an account? <a  class="btn btn-secondary" href="{% url 'blog:signup' %}">Sign up...</a></p>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

      
          


        
{% endblock %}